version: '3.8'
services:
  api-health-monitor:
    image: ryanzhi1997/api-health-monitor:latest
    container_name: api-health-monitor
    ports:
      - "2025:2025"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
